version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app:
    container_name: app
    restart: always
    build: .
    environment:
      - PORT=3000
    ports:
      - "3000"
    links:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mask-dev
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
